"""init

Revision ID: 5735013f16ac
Revises: 
Create Date: 2025-04-12 20:48:35.335663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5735013f16ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azure_ad_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usr_azure_ad_id'), 'usr', ['azure_ad_id'], unique=True)
    op.create_index(op.f('ix_usr_email'), 'usr', ['email'], unique=True)
    op.create_index(op.f('ix_usr_id'), 'usr', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usr_id'), table_name='usr')
    op.drop_index(op.f('ix_usr_email'), table_name='usr')
    op.drop_index(op.f('ix_usr_azure_ad_id'), table_name='usr')
    op.drop_table('usr')
    # ### end Alembic commands ###
