"""user azure_id

Revision ID: 6fbc769b6009
Revises: 687a39fd411b
Create Date: 2025-04-19 20:07:17.207015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbc769b6009'
down_revision: Union[str, None] = '687a39fd411b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usr', sa.Column('azure_id', sa.UUID(), nullable=True))
    op.add_column('usr', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('usr', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_usr_azure_ad_id', table_name='usr')
    op.create_index(op.f('ix_usr_azure_id'), 'usr', ['azure_id'], unique=True)
    op.drop_column('usr', 'azure_ad_id')
    op.drop_column('usr', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usr', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usr', sa.Column('azure_ad_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usr_azure_id'), table_name='usr')
    op.create_index('ix_usr_azure_ad_id', 'usr', ['azure_ad_id'], unique=True)
    op.alter_column('usr', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usr', 'name')
    op.drop_column('usr', 'azure_id')
    # ### end Alembic commands ###
