"""vectors

Revision ID: 9d0f3ef53454
Revises: 57ef7f3b3337
Create Date: 2025-05-25 08:19:49.791826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector  # pyright: ignore [reportMissingTypeStubs]


# revision identifiers, used by Alembic.
revision: str = '9d0f3ef53454'
down_revision: Union[str, None] = '57ef7f3b3337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))  # pyright: ignore [reportUnknownArgumentType, reportUnknownMemberType, reportAttributeAccessIssue]
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'vector')
    # ### end Alembic commands ###
